http:
  routers:
    nomad:
      service: nomad
      rule: Host(`homelab.dsb.dev`)
      entrypoints:
        - https
      tls:
        certresolver: cloudflare

    consul:
      service: consul
      rule: Host(`consul.homelab.dsb.dev`)
      entrypoints:
        - https
      tls:
        certresolver: cloudflare

    vault:
      service: vault
      rule: Host(`vault.homelab.dsb.dev`)
      entrypoints:
        - https
      tls:
        certresolver: cloudflare

  services:
    nomad:
      loadBalancer:
        servers:
          - url: "http://100.105.214.9:4646"
          - url: "http://100.88.254.41:4646"
          - url: "http://100.99.108.54:4646"

    consul:
      loadBalancer:
        servers:
          - url: "http://100.76.222.102:8500"

    vault:
      loadBalancer:
        servers:
          - url: "http://100.105.214.9:8200"
          - url: "http://100.88.254.41:8200"
          - url: "http://100.99.108.54:8200"
